# Key Bindings
# key name refer to `xev` or `wev` command output,
# mod keys name: super,ctrl,alt,shift,none

# reload config
bind=SUPER,r,reload_config

# exit
bind=SUPER,Escape,quit
bind=SUPER,q,killclient,

# menu and terminal
bind=SUPER,space,spawn,fuzzel
bind=SUPER,Return,spawn,foot

# applications
bind=SUPER,w,google-chrome-stable

# switch layout
bind=SUPER,l,switch_layout

# === scratchpad ===

# named scratchpad
windowrule=isnamedscratchpad:1,width:1280,height:800,appid:foot-scratchpad
bind=SUPER,p,toggle_named_scratchpad,foot-scratchpad,none,foot --app-id foot-scratchpad

# === windows ===

# switch window focus
bind=SUPER,Tab,focusstack,next
bind=SUPER,Left,focusdir,left
bind=SUPER,Right,focusdir,right
bind=SUPER,Up,focusdir,up
bind=SUPER,Down,focusdir,down

# swap window
bind=SUPER+SHIFT,Up,exchange_client,up
bind=SUPER+SHIFT,Down,exchange_client,down
bind=SUPER+SHIFT,Left,exchange_client,left
bind=SUPER+SHIFT,Right,exchange_client,right

# switch window status
bind=SUPER,g,toggleglobal,
bind=SUPER,o,toggleoverview,
bind=SUPER,backslash,togglefloating,
bind=SUPER,f,togglefullscreen,

# resizewin
bind=SUPER+CTRL+ALT,Up,resizewin,+0,-50
bind=SUPER+CTRL+ALT,Down,resizewin,+0,+50
bind=SUPER+CTRL+ALT,Left,resizewin,-50,+0
bind=SUPER+CTRL+ALT,Right,resizewin,+50,+0

# === tags ===

# tag switch
bind=ALT,Left,viewtoleft_have_client,0
bind=ALT,Right,viewtoright_have_client,0
bind=ALT,Tab,view,-1,0

bind=ALT,1,view,1,0
bind=ALT,2,view,2,0
bind=ALT,3,view,3,0
bind=ALT,4,view,4,0
bind=ALT,5,view,5,0
bind=ALT,6,view,6,0
bind=ALT,7,view,7,0
bind=ALT,8,view,8,0
bind=ALT,9,view,9,0

# tag: move client to the tag and focus it
# tagsilent: move client to the tag and not focus it
# bind=Alt,1,tagsilent,1
bind=ALT+SHIFT,1,tagsilent,1,0
bind=ALT+SHIFT,2,tagsilent,2,0
bind=ALT+SHIFT,3,tagsilent,3,0
bind=ALT+SHIFT,4,tagsilent,4,0
bind=ALT+SHIFT,5,tagsilent,5,0
bind=ALT+SHIFT,6,tagsilent,6,0
bind=ALT+SHIFT,7,tagsilent,7,0
bind=ALT+SHIFT,8,tagsilent,8,0
bind=ALT+SHIFT,9,tagsilent,9,0


# === monitors

# monitor switch
bind=CTRL,Left,focusmon,left
bind=CTRL,Right,focusmon,right
bind=CTRL+ALT,Left,tagmon,left
bind=CTRL+ALT,Right,tagmon,right

# Mouse Button Bindings
# btn_left and btn_right can't bind none mod key
mousebind=SUPER,btn_left,moveresize,curmove
mousebind=NONE,btn_middle,togglemaximizescreen,0
mousebind=SUPER,btn_right,moveresize,curresize


# Axis Bindings
axisbind=SUPER,UP,viewtoleft_have_client
axisbind=SUPER,DOWN,viewtoright_have_client


