#!/bin/sh
# template: /usr/share/river/example/init
# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.

notify-send -t 5000 "(Re)load river config"

# === options ===
# colors
riverctl background-color 0x002b36
riverctl border-color-focused 0x81a2be
riverctl border-color-unfocused 0x1D1F21
riverctl border-color-urgent 0xCC6666
riverctl border-width 2
# set keyboard repeat rate
riverctl set-repeat 50 300
# hide cursor timeout
riverctl hide-cursor timeout 0
# window focus follows mouse cursor
riverctl focus-follows-cursor normal
# place views at bottom of stack
riverctl default-attach-mode bottom

# === autostart ===
riverctl spawn 'dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river'
riverctl spawn 'systemctl --user import-environment DISPLAY WAYLAND_DISPLAY'
riverctl spawn 'systemctl --user daemon-reload'
riverctl spawn 'systemctl --user restart river-idle.service'
riverctl spawn 'systemctl --user restart river-waybar.service'

# === inputs ===
for pad in $(riverctl list-inputs | grep -i pointer)
do
  riverctl input $pad tap                   enabled
  riverctl input $pad disable-while-typing  enabled
  riverctl input $pad scroll-method         two-finger
  riverctl input $pad natural-scroll        enabled
done

# === keybinds ===
# core keybinds
riverctl map normal Super                 Q         close
riverctl map normal Super                 W         spawn 'firefox --app-id=firefox'
riverctl map normal Super                 E         exit
riverctl map normal Super                 R         spawn '~/.config/river/init'
riverctl map normal Super                 Return    spawn foot
riverctl map normal Super                 D         spawn wofi
riverctl map normal Super+Control         L         spawn swaylock
# system maintenance script
riverctl map normal None                  XF86Tools spawn 'foot --hold sys'          

# == views ==
# focus
riverctl map normal Super                 Left      focus-view previous
riverctl map normal Super                 H         focus-view previous
riverctl map normal Super                 Right     focus-view next
riverctl map normal Super                 L         focus-view next
# move
riverctl map normal Super+Shift           Left      swap previous
riverctl map normal Super+Shift           H         swap previous
riverctl map normal Super+Shift           Right     swap next
riverctl map normal Super+Shift           L         swap next
# toggle float
riverctl map normal Super+Alt             Space     toggle-float
# toggle fullscreen
riverctl map normal Super+Alt             F         toggle-fullscreen

# == tags ==
for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # focus tags
    riverctl map normal Super             $i        set-focused-tags $tags

    # move view to tag
    riverctl map normal Super+Shift       $i        set-view-tags $tags

done
# focus previous tags
riverctl map normal Super                 Space     focus-previous-tags
riverctl map normal Super                 Space     focus-previous-tags
riverctl map normal Super+Shift           Space     send-to-previous-tags
# cycle occupied tags
# > cargo install --git https://github.com/stefur/flow flow
riverctl map normal Super                 Tab       spawn 'flow cycle-tags next 32 --occupied'

# == layout stuff == 
# change main ratio
riverctl map normal Super+Alt             Left      send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super+Alt             H         send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super+Alt             Right     send-layout-cmd rivertile "main-ratio +0.05"
riverctl map normal Super+Alt             L         send-layout-cmd rivertile "main-ratio +0.05"
# Super+{Up,Right,Down,Left} to change layout orientation
riverctl map normal Super+Alt+Control     Up        send-layout-cmd rivertile "main-location top"
riverctl map normal Super+Alt+Control     Right     send-layout-cmd rivertile "main-location right"
riverctl map normal Super+Alt+Control     Down      send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super+Alt+Control     Left      send-layout-cmd rivertile "main-location left"

# == media keys ==
for mode in normal locked
do
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'osd volume inc'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'osd volume dec'
    riverctl map $mode None XF86AudioMute         spawn 'osd volume mute'

    riverctl map $mode None XF86AudioMedia        spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay         spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev         spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext         spawn 'playerctl next'

    riverctl map $mode None XF86MonBrightnessUp   spawn 'osd brightness inc'
    riverctl map $mode None XF86MonBrightnessDown spawn 'osd brightness dec'

    riverctl map $mode None XF86Display           spawn 'osd brightness --kbd'
    riverctl map $mode None XF86KbdBrightnessUp   spawn 'osd brightness --kbd'
    riverctl map $mode None XF86KbdBrightnessDown spawn 'osd brightness --kbd'
done

# === layout ===
riverctl default-layout rivertile
rivertile -view-padding 6 -outer-padding 6 &
