#!/bin/sh
# source: /usr/share/river/example/init
#
# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.

# == options

# === options.colors
riverctl background-color 0x658594
riverctl border-color-focused 0xfab387
riverctl border-color-unfocused 0x586e75
riverctl border-color-urgent 0xeba0ac
riverctl border-width 2

# === options.misc
# Set keyboard repeat rate
riverctl set-repeat 50 300
# hide cursor timeout
riverctl hide-cursor timeout 0
# window focus follows mouse cursor
riverctl focus-follows-cursor normal
# place views at bottom of stack
riverctl attach-mode bottom
# set default layout
riverctl default-layout rivertile

riverctl float-filter-add title 'btop \[float\]'

# == autostart
riverctl spawn 'systemctl --user start river-idle.service'
riverctl spawn 'systemctl --user start river-waybar.service'
riverctl spawn 'systemctl --user start udiskie.service'

# == inputs
for pad in $(riverctl list-inputs | grep -i Synaptics)
do
  riverctl input $pad tap             enabled
  riverctl input $pad scroll-method   two-finger
  riverctl input $pad natural-scroll  enabled
done

# == keybinds

# === keybinds.core
riverctl map normal Super Q         close
riverctl map normal Super W         spawn firefox
riverctl map normal Super E         exit
riverctl map normal Super R         spawn '~/.config/river/init && notify-send "river" "reload config"'
riverctl map normal Super Return    spawn kitty
riverctl map normal Super D         spawn 'wofi --show=drun --allow-images --location=top'
riverctl map normal Super+Control L spawn '~/bin/river-lock.sh'

# === keybinds.screenshots
riverctl map normal Super+Control S         spawn 'grimshot --notify save screen'
riverctl map normal Super+Control O         spawn 'grimshot --notify save output'
riverctl map normal Super+Control W         spawn 'grimshot --notify save window'
riverctl map normal Super+Control A         spawn 'grimshot --notify save area'
riverctl map normal Super+Control+Shift S   spawn 'grimshot --notify copy screen'
riverctl map normal Super+Control+Shift O   spawn 'grimshot --notify copy output'
riverctl map normal Super+Control+Shift W   spawn 'grimshot --notify copy window'
riverctl map normal Super+Control+Shift A   spawn 'grimshot --notify copy area'

# === keybinds.focus
# focus views
riverctl map normal Super Left    focus-view previous
riverctl map normal Super Down    focus-view next
riverctl map normal Super Up      focus-view previous
riverctl map normal Super Right   focus-view next
riverctl map normal Super H       focus-view previous
riverctl map normal Super J       focus-view next
riverctl map normal Super K       focus-view previous
riverctl map normal Super L       focus-view next
# focus outputs
riverctl map normal Super Period  focus-output next
riverctl map normal Super Comma   focus-output previous
# === keybinds.move
# move views (within output)
riverctl map normal Super+Shift Left    swap previous
riverctl map normal Super+Shift Down    swap next
riverctl map normal Super+Shift Up      swap previous
riverctl map normal Super+Shift Right   swap next
riverctl map normal Super+Shift H       swap previous
riverctl map normal Super+Shift J       swap next
riverctl map normal Super+Shift K       swap previous
riverctl map normal Super+Shift L       swap next
# move views (across outputs)
riverctl map normal Super+Shift Period  send-to-output next
riverctl map normal Super+Shift Comma   send-to-output previous
# move view to top of layout stack (if already at top, bump to second)
riverctl map normal Super+Shift Z       zoom

# === keybinds.resize
# change main ratio
riverctl map normal Super+Alt Left  send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super+Alt Right send-layout-cmd rivertile "main-ratio +0.05"
riverctl map normal Super+Alt H     send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super+Alt L     send-layout-cmd rivertile "main-ratio +0.05"
# resize views (forces views to float)
riverctl map normal Super+Shift+Alt Up    resize vertical   +100 
riverctl map normal Super+Shift+Alt Right resize horizontal +100
riverctl map normal Super+Shift+Alt Down  resize vertical   -100
riverctl map normal Super+Shift+Alt Left  resize horizontal -100
riverctl map normal Super+Shift+Alt K     resize vertical   +100 
riverctl map normal Super+Shift+Alt L     resize horizontal +100
riverctl map normal Super+Shift+Alt J     resize vertical   -100
riverctl map normal Super+Shift+Alt H     resize horizontal -100

# === keybinds.move
# move floating views
riverctl map normal Super+Shift+Control Up    move up     +50 
riverctl map normal Super+Shift+Control Right move right  +50
riverctl map normal Super+Shift+Control Down  move down   +50
riverctl map normal Super+Shift+Control Left  move left   +50
riverctl map normal Super+Shift+Control K     move up     +50 
riverctl map normal Super+Shift+Control L     move right  +50
riverctl map normal Super+Shift+Control J     move down   +50
riverctl map normal Super+Shift+Control H     move left   +50

# === keybinds.layout
# Super+{Up,Right,Down,Left} to change layout orientation
riverctl map normal Super+Alt+Control Up    send-layout-cmd rivertile "main-location top"
riverctl map normal Super+Alt+Control Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super+Alt+Control Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super+Alt+Control Left  send-layout-cmd rivertile "main-location left"
riverctl map normal Super+Alt+Control K     send-layout-cmd rivertile "main-location top"
riverctl map normal Super+Alt+Control L     send-layout-cmd rivertile "main-location right"
riverctl map normal Super+Alt+Control J     send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super+Alt+Control H     send-layout-cmd rivertile "main-location left"
# increase or decrease number of views in main
riverctl map normal Super+Alt M             send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Alt N             send-layout-cmd rivertile "main-count -1"
# toggle float
riverctl map normal Super+Alt Space         toggle-float
# toggle fullscreen
riverctl map normal Super+Alt F             toggle-fullscreen

# === keybinds.media
for mode in normal locked
do
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'pactl set-sink-volume @DEFAULT_SINK@ +5%'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'pactl set-sink-volume @DEFAULT_SINK@ -5%'
    riverctl map $mode None XF86AudioMute         spawn 'pactl set-sink-mute @DEFAULT_SINK@ toggle'

    riverctl map $mode None XF86AudioMedia        spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay         spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev         spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext         spawn 'playerctl next'

    riverctl map $mode None XF86MonBrightnessUp   spawn 'light -s sysfs/backlight/intel_backlight -A 10'
    riverctl map $mode None XF86MonBrightnessDown spawn 'light -s sysfs/backlight/intel_backlight -U 10'

    riverctl map $mode None XF86Display           spawn '~/bin/toggle_kbd_backlight.sh'
done

# == tags
for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # focus tag
    riverctl map normal Super $i set-focused-tags $tags

    # move view to tag
    riverctl map normal Super+Shift $i set-view-tags $tags

done

# === tags.scratchpad
scratch_tag=$((1 << 10))
riverctl map normal Super Tab toggle-focused-tags ${scratch_tag}
riverctl map normal Super+Shift Tab set-view-tags ${scratch_tag}
all_but_scratch_tag=$(( ((1 << 9) - 1) ^ $scratch_tag ))
riverctl spawn-tagmask ${all_but_scratch_tag}

# == rivertile
pkill "rivertile" || true
rivertile -view-padding 4 \
  -outer-padding 4 \
  -main-location left \
  -main-count 1 \
  -main-ratio 0.5 &
