session_name: default
windows:
  - window_name: main
    layout: tiled
    shell_command_before:
      - cd ~
      - clear
  - window_name: coopetition
    layout: even-horizontal
    shell_command_before:
      - cd ~/repos/coopetition
    panes:
    - shell_command:
      - cmd: ranger
    - shell_command:
      - cmd: clear
  - window_name: automation
    layout: even-horizontal
    shell_command_before:
      - cd ~/repos/oss-automation
    panes:
    - shell_command:
      - cmd: ranger
    - shell_command:
      - cmd: clear
  - window_name: btop
    layout: tiled
    shell_command_before:
      - cd ~
      - btop
