backend = "pulseaudio"
use_nerdfont = false
notify = true
album_column = true

# looks good with solarized colors
[theme]
background = "black"
primary = "white"
secondary = "light white"
title = "white"
playing = "light white"
playing_selected = "light white"
playing_bg = "green"
highlight = "light white"
highlight_bg = "cyan"
error = "light white"
error_bg = "red"
statusbar = "black"
statusbar_progress = "green"
statusbar_bg = "green"
cmdline = "light white"
cmdline_bg = "black"
