backend = "pulseaudio"
use_nerdfont = false
notify = true
album_column = true

# colors
[theme]
background = "default"
primary = "#cdd6f4" # text
secondary = "#bac2de" # subtext1 
title = "#74c7ec" # sapphire 
playing = "#a6e3a1" # green 
playing_selected = "#f5e0dc" # rosewater 
playing_bg = "default"
highlight = "#f5e0dc" # rosewater
highlight_bg = "#313244" 
error = "default"
error_bg = "#f38ba8"
statusbar = "#f5e0dc" # rosewater
statusbar_progress = "#74c7ec" # sapphire
statusbar_bg = "default"
cmdline = "default"
cmdline_bg = "default"
search_match = "#cdd6f4" # text
